language: java
jdk:
  - openjdk8

branches:
  only:
    - merge_branch

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x mvnw

script: "./mvnw clean install"

before_deploy:
  - zip -r autocomplete *
  - mkdir -p deploy
  - mv autocomplete.zip deploy/autocomplete.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: autocomplete-ec2-webservice
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ljh0326s@gmail.com
