language: java
jdk:
  - openjdk8

branches:
  only:
    - merge_branch

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./mvnw clean install"

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - ljh0326s@gmail.com
